security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            users:
                admin: { password: pass, roles: [ 'ROLE_USER' ] }

    firewalls:
        profiler:
            pattern:  /_profiler.*
            security: false

        wdt:
            pattern:  /_wdt.*
            security: false

        login:
            pattern:  /demo/secured/login
            security: false

        secured_area:
            pattern:    /demo/secured/.*
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
